# RetroBBS Makefile
# For Linux/UNIX/MacOS using Free Pascal Compiler

# Compiler
FPC = fpc

# Compiler flags
FPCFLAGS = -MTP -O2 -Xs -XX -CX -Fu$(SRC_DIR)

# Directories
SRC_DIR = src
BIN_DIR = bin
TEST_DIR = $(SRC_DIR)/tests
TEST_BIN_DIR = $(BIN_DIR)/tests
DEMO_DIR = $(SRC_DIR)/demos
DEMO_BIN_DIR = $(BIN_DIR)/demos
UTIL_DIR = $(SRC_DIR)/utils
UTIL_BIN_DIR = $(BIN_DIR)/utils

# Source files
MAIN_SRC = $(SRC_DIR)/retrobbs.pas
ANSI_TEST_SRC = $(TEST_DIR)/ansi/test.pas
HASH_TEST_SRC = $(TEST_DIR)/hash/test.pas
TYPE_TEST_SRC = $(TEST_DIR)/bbstypes/test.pas
USER_TEST_SRC = $(TEST_DIR)/user/test.pas
BTREE_TEST_SRC = $(TEST_DIR)/btree/test.pas
PATH_TEST_SRC = $(TEST_DIR)/path/test.pas
UI_TEST_SRC = $(TEST_DIR)/ui/test.pas
DB_TEST_SRC = $(TEST_DIR)/db/test.pas
DB_SIMPLE_SRC = $(TEST_DIR)/db/simple.pas
DB_SIZE_SRC = $(TEST_DIR)/db/size.pas
DB_MINIMAL_SRC = $(TEST_DIR)/db/minimal.pas
DB_ALL_SRC = $(TEST_DIR)/db/all.pas
LISTS_ARRAYLIST_TEST_SRC = $(TEST_DIR)/lists/arraylst.pas
LISTS_LINKEDL_TEST_SRC = $(TEST_DIR)/lists/linkedl.pas
LISTS_ALL_SRC = $(TEST_DIR)/lists/all.pas
TABLE_TEST_SRC = $(TEST_DIR)/table/test.pas
TABLE_PRIORITY_TEST_SRC = $(TEST_DIR)/table/priority.pas
TABLE_VISIBLE_TEST_SRC = $(TEST_DIR)/table/visible.pas
TABLE_FLEXCOUNT_TEST_SRC = $(TEST_DIR)/table/flexcount.pas
TABLE_MINWIDTH_TEST_SRC = $(TEST_DIR)/table/minwidth.pas
TABLE_ASSIGNMIN_TEST_SRC = $(TEST_DIR)/table/assignmin.pas
TABLE_DISTFLEX_TEST_SRC = $(TEST_DIR)/table/distflex.pas
TABLE_DISTPROP_TEST_SRC = $(TEST_DIR)/table/distprop.pas
ALL_TESTS_SRC = $(TEST_DIR)/all.pas
ANSI_DEMO_SRC = $(DEMO_DIR)/ansidemo.pas
UI_DEMO_SRC = $(DEMO_DIR)/uidemo.pas
ANSI_UNIT = $(SRC_DIR)/ansi.pas
HASH_UNIT = $(SRC_DIR)/hash.pas
BBSTYPES_UNIT = $(SRC_DIR)/bbstypes.pas
USER_UNIT = $(SRC_DIR)/user.pas
BTREE_UNIT = $(SRC_DIR)/btree.pas
PATH_UNIT = $(SRC_DIR)/path.pas
UI_UNIT = $(SRC_DIR)/ui.pas
COLORS_UNIT = $(SRC_DIR)/colors.pas
DB_UNIT = $(SRC_DIR)/db.pas
LISTS_UNIT = $(SRC_DIR)/lists.pas
TABLE_UNIT = $(SRC_DIR)/table.pas

# Utility source files
CRC16_SRC = $(UTIL_DIR)/crc16.pas
CRC16X_SRC = $(UTIL_DIR)/crc16x.pas
CRC32_SRC = $(UTIL_DIR)/crc32.pas
SHA1_SRC = $(UTIL_DIR)/sha1.pas
USERADM_SRC = $(UTIL_DIR)/useradm.pas

# Output binaries
OUTPUT = $(BIN_DIR)/retrobbs
ANSI_TEST_BIN_DIR = $(TEST_BIN_DIR)/ansi
HASH_TEST_BIN_DIR = $(TEST_BIN_DIR)/hash
TYPE_TEST_BIN_DIR = $(TEST_BIN_DIR)/bbstypes
USER_TEST_BIN_DIR = $(TEST_BIN_DIR)/user
BTREE_TEST_BIN_DIR = $(TEST_BIN_DIR)/btree
PATH_TEST_BIN_DIR = $(TEST_BIN_DIR)/path
UI_TEST_BIN_DIR = $(TEST_BIN_DIR)/ui
LISTS_TEST_BIN_DIR = $(TEST_BIN_DIR)/lists
ANSI_TEST_OUTPUT = $(ANSI_TEST_BIN_DIR)/test
HASH_TEST_OUTPUT = $(HASH_TEST_BIN_DIR)/test
TYPE_TEST_OUTPUT = $(TYPE_TEST_BIN_DIR)/test
USER_TEST_OUTPUT = $(USER_TEST_BIN_DIR)/test
BTREE_TEST_OUTPUT = $(BTREE_TEST_BIN_DIR)/test
PATH_TEST_OUTPUT = $(PATH_TEST_BIN_DIR)/test
UI_TEST_OUTPUT = $(UI_TEST_BIN_DIR)/test
DB_TEST_BIN_DIR = $(TEST_BIN_DIR)/db
DB_TEST_OUTPUT = $(DB_TEST_BIN_DIR)/test
DB_SIMPLE_OUTPUT = $(DB_TEST_BIN_DIR)/simple
DB_SIZE_OUTPUT = $(DB_TEST_BIN_DIR)/size
DB_MINIMAL_OUTPUT = $(DB_TEST_BIN_DIR)/minimal
DB_ALL_OUTPUT = $(DB_TEST_BIN_DIR)/all
LISTS_ARRAYLIST_TEST_OUTPUT = $(LISTS_TEST_BIN_DIR)/arraylst
LISTS_LINKEDL_TEST_OUTPUT = $(LISTS_TEST_BIN_DIR)/linkedl
LISTS_ALL_OUTPUT = $(LISTS_TEST_BIN_DIR)/all
TABLE_TEST_BIN_DIR = $(TEST_BIN_DIR)/table
TABLE_TEST_OUTPUT = $(TABLE_TEST_BIN_DIR)/test
TABLE_PRIORITY_TEST_OUTPUT = $(TABLE_TEST_BIN_DIR)/priority
TABLE_VISIBLE_TEST_OUTPUT = $(TABLE_TEST_BIN_DIR)/visible
TABLE_FLEXCOUNT_TEST_OUTPUT = $(TABLE_TEST_BIN_DIR)/flexcount
TABLE_MINWIDTH_TEST_OUTPUT = $(TABLE_TEST_BIN_DIR)/minwidth
TABLE_ASSIGNMIN_TEST_OUTPUT = $(TABLE_TEST_BIN_DIR)/assignmin
TABLE_DISTFLEX_TEST_OUTPUT = $(TABLE_TEST_BIN_DIR)/distflex
TABLE_DISTPROP_TEST_OUTPUT = $(TABLE_TEST_BIN_DIR)/distprop
ALL_TESTS_OUTPUT = $(TEST_BIN_DIR)/all
ANSI_DEMO_OUTPUT = $(DEMO_BIN_DIR)/ansidemo
UI_DEMO_OUTPUT = $(DEMO_BIN_DIR)/uidemo

# Utility binaries
CRC16_OUTPUT = $(UTIL_BIN_DIR)/crc16
CRC16X_OUTPUT = $(UTIL_BIN_DIR)/crc16x
CRC32_OUTPUT = $(UTIL_BIN_DIR)/crc32
SHA1_OUTPUT = $(UTIL_BIN_DIR)/sha1
USERADM_OUTPUT = $(UTIL_BIN_DIR)/useradm

# Default target
all: $(OUTPUT) utils demo test

# Create bin directory if it doesn't exist
$(BIN_DIR):
	mkdir -p $(BIN_DIR)

# Create bin/tests directory if it doesn't exist
$(TEST_BIN_DIR):
	mkdir -p $(TEST_BIN_DIR)

# Create bin/demos directory if it doesn't exist
$(DEMO_BIN_DIR):
	mkdir -p $(DEMO_BIN_DIR)

# Create bin/utils directory if it doesn't exist
$(UTIL_BIN_DIR):
	mkdir -p $(UTIL_BIN_DIR)

# Build the main program
bin: $(OUTPUT)

$(OUTPUT): $(MAIN_SRC) $(ANSI_UNIT) | $(BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(OUTPUT) $(MAIN_SRC)

# Create test binary directories
$(ANSI_TEST_BIN_DIR):
	mkdir -p $(ANSI_TEST_BIN_DIR)

$(HASH_TEST_BIN_DIR):
	mkdir -p $(HASH_TEST_BIN_DIR)

$(TYPE_TEST_BIN_DIR):
	mkdir -p $(TYPE_TEST_BIN_DIR)

$(USER_TEST_BIN_DIR):
	mkdir -p $(USER_TEST_BIN_DIR)

$(BTREE_TEST_BIN_DIR):
	mkdir -p $(BTREE_TEST_BIN_DIR)

$(PATH_TEST_BIN_DIR):
	mkdir -p $(PATH_TEST_BIN_DIR)

$(UI_TEST_BIN_DIR):
	mkdir -p $(UI_TEST_BIN_DIR)

$(LISTS_TEST_BIN_DIR):
	mkdir -p $(LISTS_TEST_BIN_DIR)

$(TABLE_TEST_BIN_DIR):
	mkdir -p $(TABLE_TEST_BIN_DIR)

# Build the ANSI test program
$(ANSI_TEST_OUTPUT): $(ANSI_TEST_SRC) $(ANSI_UNIT) | $(ANSI_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(ANSI_TEST_OUTPUT) $(ANSI_TEST_SRC)

# Build the Hash test program
$(HASH_TEST_OUTPUT): $(HASH_TEST_SRC) $(HASH_UNIT) | $(HASH_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(HASH_TEST_OUTPUT) $(HASH_TEST_SRC)

# Build the BBSTypes test program
$(TYPE_TEST_OUTPUT): $(TYPE_TEST_SRC) $(BBSTYPES_UNIT) | $(TYPE_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(TYPE_TEST_OUTPUT) $(TYPE_TEST_SRC)

# Build the User test program
$(USER_TEST_OUTPUT): $(USER_TEST_SRC) $(USER_UNIT) $(BBSTYPES_UNIT) $(HASH_UNIT) | $(USER_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(USER_TEST_OUTPUT) $(USER_TEST_SRC)

# Build the BTree test program
$(BTREE_TEST_OUTPUT): $(BTREE_TEST_SRC) $(BTREE_UNIT) $(BBSTYPES_UNIT) $(HASH_UNIT) | $(BTREE_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(BTREE_TEST_OUTPUT) $(BTREE_TEST_SRC)

# Build the Path test program
$(PATH_TEST_OUTPUT): $(PATH_TEST_SRC) $(PATH_UNIT) $(BBSTYPES_UNIT) | $(PATH_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(PATH_TEST_OUTPUT) $(PATH_TEST_SRC)

# Build the UI test program
$(UI_TEST_OUTPUT): $(UI_TEST_SRC) $(UI_UNIT) $(ANSI_UNIT) $(COLORS_UNIT) $(BBSTYPES_UNIT) | $(UI_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(UI_TEST_OUTPUT) $(UI_TEST_SRC)

# Create DB test binary directory
$(DB_TEST_BIN_DIR):
	mkdir -p $(DB_TEST_BIN_DIR)

# Build the DB test programs
$(DB_TEST_OUTPUT): $(DB_TEST_SRC) $(DB_UNIT) $(BTREE_UNIT) $(BBSTYPES_UNIT) $(HASH_UNIT) | $(DB_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(DB_TEST_OUTPUT) $(DB_TEST_SRC)

$(DB_SIMPLE_OUTPUT): $(DB_SIMPLE_SRC) $(DB_UNIT) $(BTREE_UNIT) $(BBSTYPES_UNIT) $(HASH_UNIT) | $(DB_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(DB_SIMPLE_OUTPUT) $(DB_SIMPLE_SRC)

$(DB_SIZE_OUTPUT): $(DB_SIZE_SRC) $(DB_UNIT) $(BTREE_UNIT) $(BBSTYPES_UNIT) | $(DB_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(DB_SIZE_OUTPUT) $(DB_SIZE_SRC)

$(DB_MINIMAL_OUTPUT): $(DB_MINIMAL_SRC) $(DB_UNIT) $(BTREE_UNIT) $(BBSTYPES_UNIT) $(HASH_UNIT) | $(DB_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(DB_MINIMAL_OUTPUT) $(DB_MINIMAL_SRC)

$(DB_ALL_OUTPUT): $(DB_ALL_SRC) | $(DB_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(DB_ALL_OUTPUT) $(DB_ALL_SRC)

# Build the Lists test programs
$(LISTS_ARRAYLIST_TEST_OUTPUT): $(LISTS_ARRAYLIST_TEST_SRC) $(LISTS_UNIT) $(BBSTYPES_UNIT) | $(LISTS_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(LISTS_ARRAYLIST_TEST_OUTPUT) $(LISTS_ARRAYLIST_TEST_SRC)

$(LISTS_LINKEDL_TEST_OUTPUT): $(LISTS_LINKEDL_TEST_SRC) $(LISTS_UNIT) $(BBSTYPES_UNIT) | $(LISTS_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(LISTS_LINKEDL_TEST_OUTPUT) $(LISTS_LINKEDL_TEST_SRC)

$(LISTS_ALL_OUTPUT): $(LISTS_ALL_SRC) | $(LISTS_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(LISTS_ALL_OUTPUT) $(LISTS_ALL_SRC)

# Build the Table test programs
$(TABLE_TEST_OUTPUT): $(TABLE_TEST_SRC) $(TABLE_UNIT) $(UI_UNIT) $(LISTS_UNIT) $(COLORS_UNIT) $(ANSI_UNIT) $(BBSTYPES_UNIT) | $(TABLE_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(TABLE_TEST_OUTPUT) $(TABLE_TEST_SRC)

$(TABLE_PRIORITY_TEST_OUTPUT): $(TABLE_PRIORITY_TEST_SRC) $(TABLE_UNIT) $(UI_UNIT) $(LISTS_UNIT) $(COLORS_UNIT) $(ANSI_UNIT) $(BBSTYPES_UNIT) | $(TABLE_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(TABLE_PRIORITY_TEST_OUTPUT) $(TABLE_PRIORITY_TEST_SRC)

$(TABLE_VISIBLE_TEST_OUTPUT): $(TABLE_VISIBLE_TEST_SRC) $(TABLE_UNIT) $(UI_UNIT) $(LISTS_UNIT) $(COLORS_UNIT) $(ANSI_UNIT) $(BBSTYPES_UNIT) | $(TABLE_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(TABLE_VISIBLE_TEST_OUTPUT) $(TABLE_VISIBLE_TEST_SRC)

$(TABLE_FLEXCOUNT_TEST_OUTPUT): $(TABLE_FLEXCOUNT_TEST_SRC) $(TABLE_UNIT) $(UI_UNIT) $(LISTS_UNIT) $(COLORS_UNIT) $(ANSI_UNIT) $(BBSTYPES_UNIT) | $(TABLE_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(TABLE_FLEXCOUNT_TEST_OUTPUT) $(TABLE_FLEXCOUNT_TEST_SRC)

$(TABLE_MINWIDTH_TEST_OUTPUT): $(TABLE_MINWIDTH_TEST_SRC) $(TABLE_UNIT) $(UI_UNIT) $(LISTS_UNIT) $(COLORS_UNIT) $(ANSI_UNIT) $(BBSTYPES_UNIT) | $(TABLE_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(TABLE_MINWIDTH_TEST_OUTPUT) $(TABLE_MINWIDTH_TEST_SRC)

$(TABLE_ASSIGNMIN_TEST_OUTPUT): $(TABLE_ASSIGNMIN_TEST_SRC) $(TABLE_UNIT) $(UI_UNIT) $(LISTS_UNIT) $(COLORS_UNIT) $(ANSI_UNIT) $(BBSTYPES_UNIT) | $(TABLE_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(TABLE_ASSIGNMIN_TEST_OUTPUT) $(TABLE_ASSIGNMIN_TEST_SRC)

$(TABLE_DISTFLEX_TEST_OUTPUT): $(TABLE_DISTFLEX_TEST_SRC) $(TABLE_UNIT) $(UI_UNIT) $(LISTS_UNIT) $(COLORS_UNIT) $(ANSI_UNIT) $(BBSTYPES_UNIT) | $(TABLE_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(TABLE_DISTFLEX_TEST_OUTPUT) $(TABLE_DISTFLEX_TEST_SRC)

$(TABLE_DISTPROP_TEST_OUTPUT): $(TABLE_DISTPROP_TEST_SRC) $(TABLE_UNIT) $(UI_UNIT) $(LISTS_UNIT) $(COLORS_UNIT) $(ANSI_UNIT) $(BBSTYPES_UNIT) | $(TABLE_TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(TABLE_DISTPROP_TEST_OUTPUT) $(TABLE_DISTPROP_TEST_SRC)

# Build the master test suite
$(ALL_TESTS_OUTPUT): $(ALL_TESTS_SRC) | $(TEST_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(ALL_TESTS_OUTPUT) $(ALL_TESTS_SRC)

# Build the ANSI demo program
$(ANSI_DEMO_OUTPUT): $(ANSI_DEMO_SRC) $(ANSI_UNIT) | $(DEMO_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(ANSI_DEMO_OUTPUT) $(ANSI_DEMO_SRC)

# Build the UI demo program
$(UI_DEMO_OUTPUT): $(UI_DEMO_SRC) $(ANSI_UNIT) | $(DEMO_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(UI_DEMO_OUTPUT) $(UI_DEMO_SRC)

# Build CRC16 utility
$(CRC16_OUTPUT): $(CRC16_SRC) $(HASH_UNIT) | $(UTIL_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(CRC16_OUTPUT) $(CRC16_SRC)

# Build CRC16X utility
$(CRC16X_OUTPUT): $(CRC16X_SRC) $(HASH_UNIT) | $(UTIL_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(CRC16X_OUTPUT) $(CRC16X_SRC)

# Build CRC32 utility
$(CRC32_OUTPUT): $(CRC32_SRC) $(HASH_UNIT) | $(UTIL_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(CRC32_OUTPUT) $(CRC32_SRC)

# Build SHA1 utility
$(SHA1_OUTPUT): $(SHA1_SRC) $(HASH_UNIT) | $(UTIL_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(SHA1_OUTPUT) $(SHA1_SRC)

# Build User Administration utility
$(USERADM_OUTPUT): $(USERADM_SRC) $(USER_UNIT) $(TABLE_UNIT) $(UI_UNIT) $(ANSI_UNIT) $(COLORS_UNIT) $(LISTS_UNIT) $(DB_UNIT) $(BTREE_UNIT) $(HASH_UNIT) $(BBSTYPES_UNIT) | $(UTIL_BIN_DIR)
	$(FPC) $(FPCFLAGS) -o$(USERADM_OUTPUT) $(USERADM_SRC)

# Build and run all test programs
test: tests
	$(ALL_TESTS_OUTPUT)

# Build all test programs
tests: $(ANSI_TEST_OUTPUT) $(HASH_TEST_OUTPUT) $(TYPE_TEST_OUTPUT) $(USER_TEST_OUTPUT) $(BTREE_TEST_OUTPUT) $(PATH_TEST_OUTPUT) $(UI_TEST_OUTPUT) $(DB_TEST_OUTPUT) $(DB_SIMPLE_OUTPUT) $(DB_SIZE_OUTPUT) $(DB_MINIMAL_OUTPUT) $(DB_ALL_OUTPUT) $(LISTS_ARRAYLIST_TEST_OUTPUT) $(LISTS_LINKEDL_TEST_OUTPUT) $(LISTS_ALL_OUTPUT) $(TABLE_TEST_OUTPUT) $(TABLE_PRIORITY_TEST_OUTPUT) $(TABLE_VISIBLE_TEST_OUTPUT) $(TABLE_FLEXCOUNT_TEST_OUTPUT) $(TABLE_MINWIDTH_TEST_OUTPUT) $(TABLE_ASSIGNMIN_TEST_OUTPUT) $(TABLE_DISTFLEX_TEST_OUTPUT) $(TABLE_DISTPROP_TEST_OUTPUT) $(ALL_TESTS_OUTPUT)

# Build all Path test programs
test-path: $(PATH_TEST_OUTPUT)

# Build all DB test programs
test-db: $(DB_TEST_OUTPUT) $(DB_SIMPLE_OUTPUT) $(DB_SIZE_OUTPUT) $(DB_MINIMAL_OUTPUT) $(DB_ALL_OUTPUT)

# Build all Lists test programs
test-lists: $(LISTS_ARRAYLIST_TEST_OUTPUT) $(LISTS_LINKEDL_TEST_OUTPUT) $(LISTS_ALL_OUTPUT)

# Build all Table test programs
test-table: $(TABLE_TEST_OUTPUT) $(TABLE_PRIORITY_TEST_OUTPUT) $(TABLE_VISIBLE_TEST_OUTPUT) $(TABLE_FLEXCOUNT_TEST_OUTPUT) $(TABLE_MINWIDTH_TEST_OUTPUT) $(TABLE_ASSIGNMIN_TEST_OUTPUT) $(TABLE_DISTFLEX_TEST_OUTPUT) $(TABLE_DISTPROP_TEST_OUTPUT)

# Build demo programs
demo: $(ANSI_DEMO_OUTPUT) $(UI_DEMO_OUTPUT)

# Build utility programs
utils: $(CRC16_OUTPUT) $(CRC16X_OUTPUT) $(CRC32_OUTPUT) $(SHA1_OUTPUT) $(USERADM_OUTPUT)

# Clean build artifacts
clean:
	rm -rf $(TEST_BIN_DIR)
	rm -rf $(DEMO_BIN_DIR)
	rm -rf $(UTIL_BIN_DIR)
	rm -f $(BIN_DIR)/*.o
	rm -f $(BIN_DIR)/*.ppu
	rm -f $(BIN_DIR)/retrobbs
	rm -f $(SRC_DIR)/*.o
	rm -f $(SRC_DIR)/*.ppu
	rm -f $(TEST_DIR)/*.o
	rm -f $(TEST_DIR)/*.ppu
	rm -f $(DEMO_DIR)/*.o
	rm -f $(DEMO_DIR)/*.ppu
	rm -f $(UTIL_DIR)/*.o
	rm -f $(UTIL_DIR)/*.ppu

# Clean everything including binary
distclean: clean
	rm -rf $(BIN_DIR)

# Run the main program
run: $(OUTPUT)
	$(OUTPUT)

# Run the ANSI test program
run-test: $(TEST_OUTPUT)
	$(TEST_OUTPUT)

# Run the ANSI demo program
run-demo: $(ANSI_DEMO_OUTPUT)
	$(ANSI_DEMO_OUTPUT)

.PHONY: all bin test tests test-path test-db test-lists test-table demo utils clean distclean run run-test run-demo
